### ISSUE TITLE
Set Merge Type For PR Auto-Complete

### ISSUE THREAD

**Issue by edgariscoding** [shayki5/azure-devops-create-pr-task#10]
My organization only allows Squash merge types on PRs to our master branch. Currently, if I have this extension auto-complete the PR, I get the following warning:

> Project Collection Build Service (My-Company) set the pull request to automatically complete when the following policies succeed:
> Merge type: Merge (no fast-forward) is forbidden by policy
> Changes will be merged into master. Branch develop will be retained. Work items will be unchanged.

Is there a way we could set the merge type after checking the "set auto-complete" option for the task?

**Comment by shayki5** [comment]
Hi @edgariscoding,
It's a good idea to add this feature! 
I will start work on it and I will update you.

Kind regards,
Shayki

**Comment by shayki5** [comment]
Hi again,

I added this feature :)
Now you can choose a few complete options, include squash merge.
Implemented in PR #11 

Kind regards,
Shayki

**Comment by edgariscoding** [comment]
Wow! That was fast! Thank you!

**Comment by shayki5** [comment]
You're welcome!
Please check it and if it doesn't work let me know.

**Comment by edgariscoding** [comment]
@shayki5 is there a way to force an update to a task or does it take some time for it to become available from Microsoft? I created a new pipeline and added your extension. The version drop down at the top shows "1.*" and I don't see options for choosing the merge type when enabling auto-complete.

**Comment by shayki5** [comment]
@edgariscoding It should be updated automatically within a few hours, if you not see it you can just uninstall the extension and reinstall.

**Comment by edgariscoding** [comment]
@shayki5 Just wanted to show that I still don't see these options despite having the latest version of the extension. I create a NEW empty build pipeline, then added the "Create Pull Request" task. Checking the "Set Auto Complete" does not show the options to choose a merge type.

![image](https://user-images.githubusercontent.com/12093243/68701256-fc315900-054b-11ea-877a-06f12a4dd8af.png)

![image](https://user-images.githubusercontent.com/12093243/68701278-09e6de80-054c-11ea-9b5c-691492a32f48.png)

**Comment by shayki5** [comment]
@edgariscoding It's really wired, it also occurs to me when I published a private version to test it, I think there is a bug, I should report it. what I do each time is uninstall and re-install so I guess it will solve it also in the public version.

**Comment by edgariscoding** [comment]
@shayki5 Thank you, I guess I could submit a bug report too. I'm not the administrator for our organization so I can't uninstall the extension myself. I'll see if it starts working one of these days.

**Comment by edgariscoding** [comment]
@shayki5 just a heads up, do you think the reason why the extension isn't updating is because the version listed in task.json (1.2.30) and the manifest version listed in vss-extension.json (1.2.15) do not match the version when this feature was implemented (1.2.36) or latest version listed in the Azure Marketplace (1.2.37)?

Someone mentioned this in a Stackoverflow question I was reading:
>In my case, the problem was not updating the task version in task.json file. Updating the extension's version (in the manifest file) is not enough. If the task version does not change, Azure DevOps will not update the task itself (despite correctly updating the extension in the "Extensions" page).
https://stackoverflow.com/questions/56793524/cannot-update-azure-devops-vsts-extension

**Comment by edgariscoding** [comment]
@shayki5 I still don't see the new feature, I guess I'll just wait for the next update.

**Comment by shayki5** [comment]
@edgariscoding I uploaded a new version - 1.2.40 and I updated the task version to this version, can you check if you see the update now?

**Comment by edgariscoding** [comment]
@shayki5 Yup! That worked! Thank you!

**Comment by shayki5** [comment]
Great! you're welcome :)
I will add a build step to update the task.json in each build.
Thank you!
