### ISSUE TITLE
Azure DevOps - Link Work Items

### ISSUE THREAD

**Issue by tcukanoot** [shayki5/azure-devops-create-pr-task#18]
The Pull Requests created in the Azure DevOps Release Pipeline are not automatically linking the associated work items, despite that selection being checked. 
![image](https://user-images.githubusercontent.com/37633617/71268159-e44eb100-2311-11ea-9b72-6d361a371fda.png)
Is it possible I've missed a necessary permission? No errors appear to be reported, I just have to manually add the items when I approve/complete the request.

**Comment by shayki5** [comment]
Hi @tcukanoot,
Can you run the task with `debug` = `true` and share here the logs, please?

Thank you,
Shayki

**Comment by tcukanoot** [comment]
I ran a task with 1 associated work item in the build/branch. Work item was not linked in automatically created pull request.
Create Pull Request log:

2019-12-27T20:44:25.4660665Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2019-12-27T20:44:25.4662400Z ##[debug]Evaluating: succeeded()
2019-12-27T20:44:25.4662821Z ##[debug]Evaluating succeeded:
2019-12-27T20:44:25.4663557Z ##[debug]=> True
2019-12-27T20:44:25.4663768Z ##[debug]Result: True
2019-12-27T20:44:25.4664110Z ##[section]Starting: Create Pull Request
2019-12-27T20:44:25.4782267Z ==============================================================================
2019-12-27T20:44:25.4782318Z Task         : Create Pull Request
2019-12-27T20:44:25.4782344Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2019-12-27T20:44:25.4782372Z Version      : 1.2.53
2019-12-27T20:44:25.4782415Z Author       : Shayki Abramczyk
2019-12-27T20:44:25.4782442Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2019-12-27T20:44:25.4782466Z ==============================================================================
2019-12-27T20:44:26.3303400Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2019-12-27T20:44:26.4831109Z ##[debug]Entering RunTask.
2019-12-27T20:44:26.5263875Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/development'
2019-12-27T20:44:26.5292330Z ##[debug]INPUT_TARGETBRANCH: 'DevTester'
2019-12-27T20:44:26.5391983Z ##[debug]INPUT_TITLE: 'DevTesterMerge'
2019-12-27T20:44:26.5396461Z ##[debug]INPUT_DESCRIPTION (empty)
2019-12-27T20:44:26.5410052Z ##[debug]INPUT_REVIEWERS (empty)
2019-12-27T20:44:26.5440479Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2019-12-27T20:44:26.5506113Z ##[debug]INPUT_ISDRAFT: 'false'
2019-12-27T20:44:26.5509425Z ##[debug] Converted to bool: False
2019-12-27T20:44:26.5526743Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2019-12-27T20:44:26.5545439Z ##[debug] Converted to bool: False
2019-12-27T20:44:26.5570261Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2019-12-27T20:44:26.5596761Z ##[debug]INPUT_DELETESOURCH: 'false'
2019-12-27T20:44:26.5614899Z ##[debug] Converted to bool: False
2019-12-27T20:44:26.5639913Z ##[debug]INPUT_COMMITMESSAGE (empty)
2019-12-27T20:44:26.5675211Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2019-12-27T20:44:26.5692656Z ##[debug] Converted to bool: False
2019-12-27T20:44:26.5719157Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2019-12-27T20:44:26.5735985Z ##[debug] Converted to bool: True
2019-12-27T20:44:26.6246200Z The Source Branch is: refs/heads/development
2019-12-27T20:44:26.6255190Z The Target Branch is: refs/heads/DevTester
2019-12-27T20:44:26.6265410Z The Title is: DevTesterMerge
2019-12-27T20:44:26.6274224Z The Description is: 
2019-12-27T20:44:26.6315989Z Is Draft Pull Request: False
2019-12-27T20:44:26.7786760Z ##[debug]POST https://****.visualstudio.com/****** Dashboard/_apis/git/repositories/******/commitsBatch?api-version=4.1 with -1-byte payload
2019-12-27T20:44:26.9504188Z ##[debug]received 2187-byte response of content type application/json; charset=utf-8; api-version=4.1
2019-12-27T20:44:26.9944861Z ##[debug]{
2019-12-27T20:44:26.9964618Z ##[debug]    "sourceRefName":  "refs/heads/development",
2019-12-27T20:44:26.9982675Z ##[debug]    "title":  "DevTesterMerge",
2019-12-27T20:44:27.0001332Z ##[debug]    "WorkItemRefs":  [
2019-12-27T20:44:27.0019698Z ##[debug]                         {
2019-12-27T20:44:27.0031992Z ##[debug]                             "id":  null,
2019-12-27T20:44:27.0051774Z ##[debug]                             "url":  ""
2019-12-27T20:44:27.0068301Z ##[debug]                         }
2019-12-27T20:44:27.0084717Z ##[debug]                     ],
2019-12-27T20:44:27.0102661Z ##[debug]    "description":  "",
2019-12-27T20:44:27.0812603Z ##[debug]    "reviewers":  "",
2019-12-27T20:44:27.1207437Z ##[debug]    "isDraft":  "False",
2019-12-27T20:44:27.1207954Z ##[debug]    "targetRefName":  "refs/heads/DevTester"
2019-12-27T20:44:27.1208185Z ##[debug]}
2019-12-27T20:44:27.1208373Z ##[debug]https://******.visualstudio.com/******/_apis/git/repositories/******/pullrequests?api-version=5.0
2019-12-27T20:44:27.1211175Z ##[debug]POST https://******.visualstudio.com/******/_apis/git/repositories/******/pullrequests?api-version=5.0 with -1-byte payload
2019-12-27T20:44:28.3827088Z ##[debug]received 4572-byte response of content type application/json; charset=utf-8; api-version=5.0
2019-12-27T20:44:28.3864369Z *************************
2019-12-27T20:44:28.3874608Z ******** Success ********
2019-12-27T20:44:28.3880658Z *************************
2019-12-27T20:44:28.3888282Z Pull Request 790 created.
2019-12-27T20:44:28.3915594Z ##[debug]Leaving RunTask.
2019-12-27T20:44:28.4176808Z ##[section]Finishing: Create Pull Request

**Comment by shayki5** [comment]
Hi,
I added some debug prints, please run the task again with the `system.debug = true` and share again the results.
Thank you!

**Comment by tcukanoot** [comment]
new logs attached:
2019-12-30T15:48:49.7307111Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2019-12-30T15:48:49.7307892Z ##[debug]Evaluating: succeeded()
2019-12-30T15:48:49.7308002Z ##[debug]Evaluating succeeded:
2019-12-30T15:48:49.7308355Z ##[debug]=> True
2019-12-30T15:48:49.7309156Z ##[debug]Result: True
2019-12-30T15:48:49.7309402Z ##[section]Starting: Create Pull Request
2019-12-30T15:48:49.7423720Z ==============================================================================
2019-12-30T15:48:49.7423812Z Task         : Create Pull Request
2019-12-30T15:48:49.7423845Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2019-12-30T15:48:49.7423878Z Version      : 1.2.54
2019-12-30T15:48:49.7423908Z Author       : Shayki Abramczyk
2019-12-30T15:48:49.7423947Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2019-12-30T15:48:49.7459045Z ==============================================================================
2019-12-30T15:48:50.7235434Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2019-12-30T15:48:50.9105266Z ##[debug]Entering RunTask.
2019-12-30T15:48:50.9456795Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/development'
2019-12-30T15:48:50.9489995Z ##[debug]INPUT_TARGETBRANCH: 'DevTester'
2019-12-30T15:48:50.9551029Z ##[debug]INPUT_TITLE: 'DevTesterMerge'
2019-12-30T15:48:50.9597787Z ##[debug]INPUT_DESCRIPTION (empty)
2019-12-30T15:48:50.9624139Z ##[debug]INPUT_REVIEWERS (empty)
2019-12-30T15:48:50.9654549Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2019-12-30T15:48:50.9717075Z ##[debug]INPUT_ISDRAFT: 'false'
2019-12-30T15:48:50.9727503Z ##[debug] Converted to bool: False
2019-12-30T15:48:50.9757041Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2019-12-30T15:48:50.9779568Z ##[debug] Converted to bool: False
2019-12-30T15:48:50.9813899Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2019-12-30T15:48:50.9845470Z ##[debug]INPUT_DELETESOURCH: 'false'
2019-12-30T15:48:50.9867542Z ##[debug] Converted to bool: False
2019-12-30T15:48:50.9899791Z ##[debug]INPUT_COMMITMESSAGE (empty)
2019-12-30T15:48:50.9932042Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2019-12-30T15:48:50.9955872Z ##[debug] Converted to bool: False
2019-12-30T15:48:50.9989490Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2019-12-30T15:48:51.0011151Z ##[debug] Converted to bool: True
2019-12-30T15:48:51.0653854Z The Source Branch is: refs/heads/development
2019-12-30T15:48:51.0660873Z The Target Branch is: refs/heads/DevTester
2019-12-30T15:48:51.0670461Z The Title is: DevTesterMerge
2019-12-30T15:48:51.0680149Z The Description is: 
2019-12-30T15:48:51.0727735Z Is Draft Pull Request: False
2019-12-30T15:48:51.2632825Z ##[debug]{
2019-12-30T15:48:51.2649772Z ##[debug]    "compareVersion":  {
2019-12-30T15:48:51.2665237Z ##[debug]                           "versionOptions":  0,
2019-12-30T15:48:51.2682474Z ##[debug]                           "versionType":  0,
2019-12-30T15:48:51.2696753Z ##[debug]                           "version":  "development"
2019-12-30T15:48:51.2711848Z ##[debug]                       },
2019-12-30T15:48:51.2726668Z ##[debug]    "itemVersion":  {
2019-12-30T15:48:51.2744626Z ##[debug]                        "versionOptions":  0,
2019-12-30T15:48:51.2764005Z ##[debug]                        "versionType":  0,
2019-12-30T15:48:51.2786036Z ##[debug]                        "version":  "DevTester"
2019-12-30T15:48:51.2796793Z ##[debug]                    },
2019-12-30T15:48:51.2814228Z ##[debug]    "$top":  101,
2019-12-30T15:48:51.3844195Z ##[debug]    "includeWorkItems":  "true"
2019-12-30T15:48:51.4003036Z ##[debug]}
2019-12-30T15:48:51.4269916Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/commitsBatch?api-version=4.1 with -1-byte payload
2019-12-30T15:48:51.5110604Z ##[debug]received 2936-byte response of content type application/json; charset=utf-8; api-version=4.1
2019-12-30T15:48:51.5203392Z ##[debug]@{count=4; value=System.Object[]}
2019-12-30T15:48:51.5666887Z ##[debug]{
2019-12-30T15:48:51.5681785Z ##[debug]    "sourceRefName":  "refs/heads/development",
2019-12-30T15:48:51.5695078Z ##[debug]    "title":  "DevTesterMerge",
2019-12-30T15:48:51.5708299Z ##[debug]    "WorkItemRefs":  [
2019-12-30T15:48:51.5721918Z ##[debug]                         {
2019-12-30T15:48:51.5733917Z ##[debug]                             "id":  null,
2019-12-30T15:48:51.5746987Z ##[debug]                             "url":  ""
2019-12-30T15:48:51.5759181Z ##[debug]                         },
2019-12-30T15:48:51.5773271Z ##[debug]                         {
2019-12-30T15:48:51.5785985Z ##[debug]                             "id":  null,
2019-12-30T15:48:51.5804765Z ##[debug]                             "url":  ""
2019-12-30T15:48:51.5818252Z ##[debug]                         }
2019-12-30T15:48:51.5831719Z ##[debug]                     ],
2019-12-30T15:48:51.5845768Z ##[debug]    "description":  "",
2019-12-30T15:48:51.5860196Z ##[debug]    "reviewers":  "",
2019-12-30T15:48:51.5874131Z ##[debug]    "isDraft":  "False",
2019-12-30T15:48:51.5888553Z ##[debug]    "targetRefName":  "refs/heads/DevTester"
2019-12-30T15:48:51.5942220Z ##[debug]}
2019-12-30T15:48:51.5942848Z ##[debug]https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/pullrequests?api-version=5.0
2019-12-30T15:48:51.5943271Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/pullrequests?api-version=5.0 with -1-byte payload
2019-12-30T15:48:52.2929845Z ##[debug]received 4572-byte response of content type application/json; charset=utf-8; api-version=5.0
2019-12-30T15:48:52.2971555Z *************************
2019-12-30T15:48:52.2978371Z ******** Success ********
2019-12-30T15:48:52.2986340Z *************************
2019-12-30T15:48:52.2996571Z Pull Request 793 created.
2019-12-30T15:48:52.3023211Z ##[debug]Leaving RunTask.
2019-12-30T15:48:52.3343175Z ##[section]Finishing: Create Pull Request
![debug](https://user-images.githubusercontent.com/37633617/71590298-867a5000-2aed-11ea-8727-299569269928.png)

**Comment by shayki5** [comment]
Thank you!
Now I figure out what is the issue, it's because you use the old URL - `xxx.visualstudio.com` instead of the new URL - `dev.azure.com/xxx`.
I fixed it and I uploaded a new version, now it should work, please check :)

**Comment by tcukanoot** [comment]
That makes sense...I've been meaning to update to the new URL at some point. I really appreciate the help.
I've run the test again, and now the task fails with following error:
Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported. 

Log:
2019-12-30T22:42:39.9992674Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2019-12-30T22:42:39.9993597Z ##[debug]Evaluating: succeeded()
2019-12-30T22:42:39.9993726Z ##[debug]Evaluating succeeded:
2019-12-30T22:42:39.9994079Z ##[debug]=> True
2019-12-30T22:42:39.9994319Z ##[debug]Result: True
2019-12-30T22:42:39.9994535Z ##[section]Starting: Create Pull Request
2019-12-30T22:42:40.0105130Z ==============================================================================
2019-12-30T22:42:40.0105214Z Task         : Create Pull Request
2019-12-30T22:42:40.0105249Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2019-12-30T22:42:40.0105284Z Version      : 1.2.55
2019-12-30T22:42:40.0105332Z Author       : Shayki Abramczyk
2019-12-30T22:42:40.0105365Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2019-12-30T22:42:40.0105397Z ==============================================================================
2019-12-30T22:42:41.0194302Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2019-12-30T22:42:41.1858844Z ##[debug]Entering RunTask.
2019-12-30T22:42:41.2146934Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/development'
2019-12-30T22:42:41.2173126Z ##[debug]INPUT_TARGETBRANCH: 'DevTester'
2019-12-30T22:42:41.2275204Z ##[debug]INPUT_TITLE: 'DevTesterMerge'
2019-12-30T22:42:41.2275921Z ##[debug]INPUT_DESCRIPTION (empty)
2019-12-30T22:42:41.2276377Z ##[debug]INPUT_REVIEWERS (empty)
2019-12-30T22:42:41.2296113Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2019-12-30T22:42:41.2372136Z ##[debug]INPUT_ISDRAFT: 'false'
2019-12-30T22:42:41.2372842Z ##[debug] Converted to bool: False
2019-12-30T22:42:41.2381726Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2019-12-30T22:42:41.2399133Z ##[debug] Converted to bool: False
2019-12-30T22:42:41.2424089Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2019-12-30T22:42:41.2449582Z ##[debug]INPUT_DELETESOURCH: 'false'
2019-12-30T22:42:41.2468212Z ##[debug] Converted to bool: False
2019-12-30T22:42:41.2494860Z ##[debug]INPUT_COMMITMESSAGE (empty)
2019-12-30T22:42:41.2520600Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2019-12-30T22:42:41.2542234Z ##[debug] Converted to bool: False
2019-12-30T22:42:41.2568474Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2019-12-30T22:42:41.2591637Z ##[debug] Converted to bool: True
2019-12-30T22:42:41.3125198Z The Source Branch is: refs/heads/development
2019-12-30T22:42:41.3131338Z The Target Branch is: refs/heads/DevTester
2019-12-30T22:42:41.3137780Z The Title is: DevTesterMerge
2019-12-30T22:42:41.3144083Z The Description is: 
2019-12-30T22:42:41.3185003Z Is Draft Pull Request: False
2019-12-30T22:42:41.4688932Z ##[debug]{
2019-12-30T22:42:41.4702470Z ##[debug]    "compareVersion":  {
2019-12-30T22:42:41.4716900Z ##[debug]                           "versionOptions":  0,
2019-12-30T22:42:41.4729083Z ##[debug]                           "versionType":  0,
2019-12-30T22:42:41.4743899Z ##[debug]                           "version":  "development"
2019-12-30T22:42:41.4756668Z ##[debug]                       },
2019-12-30T22:42:41.4769388Z ##[debug]    "itemVersion":  {
2019-12-30T22:42:41.4781160Z ##[debug]                        "versionOptions":  0,
2019-12-30T22:42:41.4793078Z ##[debug]                        "versionType":  0,
2019-12-30T22:42:41.4816180Z ##[debug]                        "version":  "DevTester"
2019-12-30T22:42:41.4830628Z ##[debug]                    },
2019-12-30T22:42:41.4843658Z ##[debug]    "$top":  101,
2019-12-30T22:42:41.5855283Z ##[debug]    "includeWorkItems":  "true"
2019-12-30T22:42:41.6042650Z ##[debug]}
2019-12-30T22:42:41.6176910Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/commitsBatch?api-version=4.1 with -1-byte payload
2019-12-30T22:42:41.7132157Z ##[debug]received 3685-byte response of content type application/json; charset=utf-8; api-version=4.1
2019-12-30T22:42:41.7165786Z ##[debug]@{count=5; value=System.Object[]}
2019-12-30T22:42:41.8217319Z ##[debug]Leaving RunTask.
2019-12-30T22:42:41.8451436Z ##[debug]Caught exception from task script.
2019-12-30T22:42:41.8487280Z ##[debug]Error record:
2019-12-30T22:42:41.9044331Z ##[debug]GetLinkedWorkItems : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
2019-12-30T22:42:41.9056277Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1:241 char:22
2019-12-30T22:42:41.9069099Z ##[debug]+ ... workItems = GetLinkedWorkItems -sourceBranch $sourceBranch.Remove(0,  ...
2019-12-30T22:42:41.9080737Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-12-30T22:42:41.9092016Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [GetLinkedWorkItems], ParameterBindingException
2019-12-30T22:42:41.9105145Z ##[debug]    + FullyQualifiedErrorId : CannotConvertArgument,GetLinkedWorkItems
2019-12-30T22:42:41.9118033Z ##[debug] 
2019-12-30T22:42:41.9187370Z ##[debug]Script stack trace:
2019-12-30T22:42:41.9188151Z ##[debug]at GetLinkedWorkItems, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 343
2019-12-30T22:42:41.9188668Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 241
2019-12-30T22:42:41.9189075Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 80
2019-12-30T22:42:41.9199781Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 38
2019-12-30T22:42:41.9211325Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 429
2019-12-30T22:42:41.9222735Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-12-30T22:42:41.9234132Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-12-30T22:42:41.9245284Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-12-30T22:42:41.9257483Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-12-30T22:42:41.9279121Z ##[debug]Exception:
2019-12-30T22:42:41.9865168Z ##[debug]System.Management.Automation.ParameterBindingException: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported. ---> System.NotSupportedException: Specified method is not supported.
2019-12-30T22:42:41.9866101Z ##[debug]   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
2019-12-30T22:42:41.9866422Z ##[debug]   --- End of inner exception stack trace ---
2019-12-30T22:42:41.9866638Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-12-30T22:42:41.9866964Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-12-30T22:42:41.9867243Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-12-30T22:42:41.9867589Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-12-30T22:42:41.9867877Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-12-30T22:42:41.9868087Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-12-30T22:42:41.9868362Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2019-12-30T22:42:41.9868563Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2019-12-30T22:42:41.9869746Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2019-12-30T22:42:41.9917285Z ##[error]Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
2019-12-30T22:42:41.9924381Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
2019-12-30T22:42:42.0028764Z ##[debug]Processed: ##vso[task.complete result=Failed]
2019-12-30T22:42:42.0523153Z ##[section]Finishing: Create Pull Request

**Comment by shayki5** [comment]
Oh ok, thanks for the update, I realized what I did wrong.
I fixed it, please check now :)

**Comment by dmundra** [comment]
The error 'Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.' no longer appears.

**Comment by shayki5** [comment]
Great :)
Does everything works well? can I close this issue?

**Comment by dmundra** [comment]
> Great :)
> Does everything work well? can I close this issue?

Question for @tcukanoot

**Comment by tcukanoot** [comment]
Apologies for the delay. I'm back to testing, and I still do not get the linked Work Items (image below). Perhaps I'm doing it incorrectly, not linking tickets properly, or don't have the most-recent version? Here is my CI/CD process:
1. build solution in visual studio, and push to new dev ops branch. 
2. I create a pull request into 'development' branch, and link the appropriate work item to this pull request. 
3. Approve the pull request and the build pipeline is automatically started
4. Successful build automatically starts the Release pipeline, which releases the web app to azure, and then kicks off this pull request task to a branch called 'DevTester'

![image](https://user-images.githubusercontent.com/37633617/71825511-a8ca1b80-3061-11ea-8c59-31b5e730b9c1.png)

2020-01-06T14:43:01.0122207Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-01-06T14:43:01.0123286Z ##[debug]Evaluating: succeeded()
2020-01-06T14:43:01.0123386Z ##[debug]Evaluating succeeded:
2020-01-06T14:43:01.0123780Z ##[debug]=> True
2020-01-06T14:43:01.0124005Z ##[debug]Result: True
2020-01-06T14:43:01.0124236Z ##[section]Starting: Create Pull Request
2020-01-06T14:43:01.0236800Z ==============================================================================
2020-01-06T14:43:01.0236859Z Task         : Create Pull Request
2020-01-06T14:43:01.0236888Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-01-06T14:43:01.0236918Z Version      : 1.2.56
2020-01-06T14:43:01.0236961Z Author       : Shayki Abramczyk
2020-01-06T14:43:01.0236988Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-01-06T14:43:01.0237015Z ==============================================================================
2020-01-06T14:43:02.0018746Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-01-06T14:43:02.1954068Z ##[debug]Entering RunTask.
2020-01-06T14:43:02.2289355Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/development'
2020-01-06T14:43:02.2319334Z ##[debug]INPUT_TARGETBRANCH: 'DevTester'
2020-01-06T14:43:02.2423713Z ##[debug]INPUT_TITLE: 'DevTesterMerge'
2020-01-06T14:43:02.2424596Z ##[debug]INPUT_DESCRIPTION (empty)
2020-01-06T14:43:02.2443531Z ##[debug]INPUT_REVIEWERS (empty)
2020-01-06T14:43:02.2473959Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-01-06T14:43:02.2543687Z ##[debug]INPUT_ISDRAFT: 'false'
2020-01-06T14:43:02.2544372Z ##[debug] Converted to bool: False
2020-01-06T14:43:02.2567564Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2020-01-06T14:43:02.2589317Z ##[debug] Converted to bool: False
2020-01-06T14:43:02.2628287Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-01-06T14:43:02.2660972Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-01-06T14:43:02.2682440Z ##[debug] Converted to bool: False
2020-01-06T14:43:02.2711350Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-01-06T14:43:02.2745613Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-01-06T14:43:02.2768685Z ##[debug] Converted to bool: False
2020-01-06T14:43:02.2799421Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-01-06T14:43:02.2820797Z ##[debug] Converted to bool: True
2020-01-06T14:43:02.3341095Z The Source Branch is: refs/heads/development
2020-01-06T14:43:02.3355671Z The Target Branch is: refs/heads/DevTester
2020-01-06T14:43:02.3363894Z The Title is: DevTesterMerge
2020-01-06T14:43:02.3373924Z The Description is: 
2020-01-06T14:43:02.3417213Z Is Draft Pull Request: False
2020-01-06T14:43:02.4924790Z ##[debug]{
2020-01-06T14:43:02.4939898Z ##[debug]    "compareVersion":  {
2020-01-06T14:43:02.4955000Z ##[debug]                           "versionOptions":  0,
2020-01-06T14:43:02.4969524Z ##[debug]                           "versionType":  0,
2020-01-06T14:43:02.4984348Z ##[debug]                           "version":  "development"
2020-01-06T14:43:02.4999048Z ##[debug]                       },
2020-01-06T14:43:02.5014211Z ##[debug]    "itemVersion":  {
2020-01-06T14:43:02.5029521Z ##[debug]                        "versionOptions":  0,
2020-01-06T14:43:02.5044259Z ##[debug]                        "versionType":  0,
2020-01-06T14:43:02.5059175Z ##[debug]                        "version":  "DevTester"
2020-01-06T14:43:02.5076558Z ##[debug]                    },
2020-01-06T14:43:02.5090811Z ##[debug]    "$top":  101,
2020-01-06T14:43:02.6130878Z ##[debug]    "includeWorkItems":  "true"
2020-01-06T14:43:02.6274652Z ##[debug]}
2020-01-06T14:43:02.6468901Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/commitsBatch?api-version=4.1 with -1-byte payload
2020-01-06T14:43:02.8746834Z ##[debug]received 4448-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-01-06T14:43:02.8781779Z ##[debug]@{count=6; value=System.Object[]}
2020-01-06T14:43:02.9054011Z ##[debug]{
2020-01-06T14:43:02.9067759Z ##[debug]    "sourceRefName":  "refs/heads/development",
2020-01-06T14:43:02.9080761Z ##[debug]    "title":  "DevTesterMerge",
2020-01-06T14:43:02.9093536Z ##[debug]    "WorkItemRefs":  [
2020-01-06T14:43:02.9106558Z ##[debug]                         {
2020-01-06T14:43:02.9120174Z ##[debug]                             "id":  "499",
2020-01-06T14:43:02.9134207Z ##[debug]                             "url":  ""
2020-01-06T14:43:02.9147392Z ##[debug]                         },
2020-01-06T14:43:02.9160486Z ##[debug]                         {
2020-01-06T14:43:02.9173476Z ##[debug]                             "id":  "499",
2020-01-06T14:43:02.9186318Z ##[debug]                             "url":  ""
2020-01-06T14:43:02.9199118Z ##[debug]                         },
2020-01-06T14:43:02.9211802Z ##[debug]                         {
2020-01-06T14:43:02.9223891Z ##[debug]                             "id":  "499",
2020-01-06T14:43:02.9238332Z ##[debug]                             "url":  ""
2020-01-06T14:43:02.9250485Z ##[debug]                         },
2020-01-06T14:43:02.9263119Z ##[debug]                         {
2020-01-06T14:43:02.9323716Z ##[debug]                             "id":  "499",
2020-01-06T14:43:02.9324379Z ##[debug]                             "url":  ""
2020-01-06T14:43:02.9324880Z ##[debug]                         }
2020-01-06T14:43:02.9325336Z ##[debug]                     ],
2020-01-06T14:43:02.9325707Z ##[debug]    "description":  "",
2020-01-06T14:43:02.9326049Z ##[debug]    "reviewers":  "",
2020-01-06T14:43:02.9336338Z ##[debug]    "isDraft":  "False",
2020-01-06T14:43:02.9349043Z ##[debug]    "targetRefName":  "refs/heads/DevTester"
2020-01-06T14:43:02.9361820Z ##[debug]}
2020-01-06T14:43:02.9385927Z ##[debug]https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/pullrequests?api-version=5.0
2020-01-06T14:43:03.9223221Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/pullrequests?api-version=5.0 with -1-byte payload
2020-01-06T14:43:03.9442616Z ##[debug]received 4571-byte response of content type application/json; charset=utf-8; api-version=5.0
2020-01-06T14:43:03.9484112Z *************************
2020-01-06T14:43:03.9492033Z ******** Success ********
2020-01-06T14:43:03.9499592Z *************************
2020-01-06T14:43:03.9508166Z Pull Request 796 created.
2020-01-06T14:43:03.9552571Z ##[debug]Leaving RunTask.
2020-01-06T14:43:03.9848347Z ##[section]Finishing: Create Pull Request

**Comment by shayki5** [comment]
In this screen (the new PR) you have "commits" tab you have a commits list, please click on their SHA (on the right side) to open their details, can you see in one commit or more that they associate to a work item?  
For example:
![image](https://user-images.githubusercontent.com/26063853/71826732-4431af80-30a7-11ea-98c0-db916d745e39.png)

**Comment by tcukanoot** [comment]
Yes, the work item appears to be linked in the most-recent commit:
![image](https://user-images.githubusercontent.com/37633617/71831506-a3270280-306e-11ea-88d8-7c701da5a519.png)

Not all of the commits have a work item though.

**Comment by shayki5** [comment]
@tcukanoot now I caught the issue! because you have many commits to the same work item the PR tried to add the same work item many times and he can't do that so he didn't link anyone, I fixed it and now it should work, please check :)

**Comment by tcukanoot** [comment]
Success! Thank you.
What I've found now though, is that I had 2 work items in the release, and only 1 of them mapped to the pull request. I will try again with a fresh set, and post logs if I'm able to reproduce.

Thanks again.

**Comment by tcukanoot** [comment]
I have confirmed that if there is more than 1 ticket attached in a release, only 1 of them makes it to the automatically generated pull request. Log attached.

2020-01-10T22:19:46.6743367Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2020-01-10T22:19:46.6744446Z ##[debug]Evaluating: succeeded()
2020-01-10T22:19:46.6744559Z ##[debug]Evaluating succeeded:
2020-01-10T22:19:46.6744925Z ##[debug]=> True
2020-01-10T22:19:46.6745193Z ##[debug]Result: True
2020-01-10T22:19:46.6745441Z ##[section]Starting: Create Pull Request
2020-01-10T22:19:46.6872972Z ==============================================================================
2020-01-10T22:19:46.6873062Z Task         : Create Pull Request
2020-01-10T22:19:46.6873098Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-01-10T22:19:46.6873133Z Version      : 1.2.58
2020-01-10T22:19:46.6873166Z Author       : Shayki Abramczyk
2020-01-10T22:19:46.6873215Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-01-10T22:19:46.6873249Z ==============================================================================
2020-01-10T22:19:47.6932433Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-01-10T22:19:47.8856741Z ##[debug]Entering RunTask.
2020-01-10T22:19:47.9186997Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/development'
2020-01-10T22:19:47.9217108Z ##[debug]INPUT_TARGETBRANCH: 'DevTester'
2020-01-10T22:19:47.9317270Z ##[debug]INPUT_TITLE: 'DevTesterMerge'
2020-01-10T22:19:47.9325218Z ##[debug]INPUT_DESCRIPTION (empty)
2020-01-10T22:19:47.9353705Z ##[debug]INPUT_REVIEWERS (empty)
2020-01-10T22:19:47.9386723Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-01-10T22:19:47.9467502Z ##[debug]INPUT_ISDRAFT: 'false'
2020-01-10T22:19:47.9468291Z ##[debug] Converted to bool: False
2020-01-10T22:19:47.9489686Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2020-01-10T22:19:47.9513371Z ##[debug] Converted to bool: False
2020-01-10T22:19:47.9545379Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-01-10T22:19:47.9575907Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-01-10T22:19:47.9595532Z ##[debug] Converted to bool: False
2020-01-10T22:19:47.9630075Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-01-10T22:19:47.9664739Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-01-10T22:19:47.9685302Z ##[debug] Converted to bool: False
2020-01-10T22:19:47.9713481Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-01-10T22:19:47.9735594Z ##[debug] Converted to bool: True
2020-01-10T22:19:48.0258074Z The Source Branch is: refs/heads/development
2020-01-10T22:19:48.0264019Z The Target Branch is: refs/heads/DevTester
2020-01-10T22:19:48.0271014Z The Title is: DevTesterMerge
2020-01-10T22:19:48.0280378Z The Description is: 
2020-01-10T22:19:48.0324951Z Is Draft Pull Request: False
2020-01-10T22:19:48.1567932Z ##[debug]{
2020-01-10T22:19:48.1584106Z ##[debug]    "compareVersion":  {
2020-01-10T22:19:48.1599591Z ##[debug]                           "versionOptions":  0,
2020-01-10T22:19:48.1614942Z ##[debug]                           "versionType":  0,
2020-01-10T22:19:48.1630179Z ##[debug]                           "version":  "development"
2020-01-10T22:19:48.1646479Z ##[debug]                       },
2020-01-10T22:19:48.1661171Z ##[debug]    "itemVersion":  {
2020-01-10T22:19:48.1674440Z ##[debug]                        "versionOptions":  0,
2020-01-10T22:19:48.1690030Z ##[debug]                        "versionType":  0,
2020-01-10T22:19:48.1704445Z ##[debug]                        "version":  "DevTester"
2020-01-10T22:19:48.1718301Z ##[debug]                    },
2020-01-10T22:19:48.1733334Z ##[debug]    "$top":  101,
2020-01-10T22:19:48.3107087Z ##[debug]    "includeWorkItems":  "true"
2020-01-10T22:19:48.3107248Z ##[debug]}
2020-01-10T22:19:48.3351003Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/commitsBatch?api-version=4.1 with -1-byte payload
2020-01-10T22:19:48.6563059Z ##[debug]received 858-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-01-10T22:19:48.6593394Z ##[debug]@{count=1; value=System.Object[]}
2020-01-10T22:19:48.9301332Z ##[debug]{
2020-01-10T22:19:48.9316283Z ##[debug]    "sourceRefName":  "refs/heads/development",
2020-01-10T22:19:48.9330084Z ##[debug]    "title":  "DevTesterMerge",
2020-01-10T22:19:48.9344068Z ##[debug]    "WorkItemRefs":  [
2020-01-10T22:19:48.9360186Z ##[debug]                         {
2020-01-10T22:19:48.9373186Z ##[debug]                             "id":  "529",
2020-01-10T22:19:48.9386750Z ##[debug]                             "url":  ""
2020-01-10T22:19:48.9399352Z ##[debug]                         }
2020-01-10T22:19:48.9412235Z ##[debug]                     ],
2020-01-10T22:19:48.9428188Z ##[debug]    "description":  "",
2020-01-10T22:19:48.9440691Z ##[debug]    "reviewers":  "",
2020-01-10T22:19:48.9454014Z ##[debug]    "isDraft":  "False",
2020-01-10T22:19:48.9472345Z ##[debug]    "targetRefName":  "refs/heads/DevTester"
2020-01-10T22:19:48.9487368Z ##[debug]}
2020-01-10T22:19:48.9511098Z ##[debug]https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/pullrequests?api-version=5.0
2020-01-10T22:19:48.9537246Z ##[debug]POST https://xxxxxx.visualstudio.com/xxxxxx/_apis/git/repositories/xxxxxx/pullrequests?api-version=5.0 with -1-byte payload
2020-01-10T22:19:49.3408379Z ##[debug]received 4665-byte response of content type application/json; charset=utf-8; api-version=5.0
2020-01-10T22:19:49.3452842Z *************************
2020-01-10T22:19:49.3459833Z ******** Success ********
2020-01-10T22:19:49.3466594Z *************************
2020-01-10T22:19:49.3475263Z Pull Request 812 created.
2020-01-10T22:19:49.3503626Z ##[debug]Leaving RunTask.
2020-01-10T22:19:49.3819971Z ##[section]Finishing: Create Pull Request

**Comment by shayki5** [comment]
Hi @tcukanoot,
Thank you for reporting it! I can reproduce it.
I fixed it and it looks like it works well now, please check :)

**Comment by tcukanoot** [comment]
Hi @shayki5 
I tested again this morning and both tickets flowed through as expected. Unless you'd like me to test any more scenarios, I think you can close this ticket. Thanks again, this is a great feature.

**Comment by shayki5** [comment]
You're welcome!
Thank you for the test!
If it will do issues in the future you can respond here.
