### ISSUE TITLE
(404) Not Found error when you add approver in Azure DevOps Server 2019

### ISSUE THREAD

**Issue by kulmam92** [shayki5/azure-devops-create-pr-task#32]
I got (404) Not Found error when you add approver in Azure DevOps Server 2019

Below is the debug message
```
2020-03-17T21:09:47.6555011Z ##[debug]https://tfs/LDTS/_apis/userentitlements?api-version=4.1-preview.1
2020-03-17T21:09:47.6678126Z ##[debug]GET https://tfs/LDTS/_apis/userentitlements?api-version=4.1-preview.1 with 0-byte payload
```

User Entitlements API doesn't exist in Azure DevOps Server 2019.
You may use "_apis/IdentityPicker/Identities" instead.
Would it be possible to fix this?

**Comment by shayki5** [comment]
Hi @kulmam92,

Thank you for reporting that!
It's wired, I quite sure I did it with `?api-version=4.1-preview.1` because Azure DevOps Server and it worked in the past, so maybe Microsoft removed the support in this version... :/
I will check how can I fix it.

Kind regards,
Shayki

**Comment by shayki5** [comment]
Hi @kulmam92  again :)
Please see issue #3 (I also mentioned it in the Known Issues), I don't remember why but I thought I fixed it, but now I see that is not tested and the commit that fixed it not so clear, so maybe it still an issue.
I will check if it could be fixed.

**Comment by shayki5** [comment]
Hi,
I think i fixed it but I can't test it, could you check if it works now?
(Check that you have the new version - 1.2.81)

**Comment by kulmam92** [comment]
@shayki5 I was able to test just now.

I encountered several issues.

1. Bug in  GetReviewerId
GitSample project was hardcoded.

2. Clinet authentication required error.
> TF400813: Resource not available for anonymous access. Client authentication required. - Azure DevOps Server

I created the System_AccessToken variable and granted the permission but still getting this error.
Therefore, I changed it to "-UseDefaultCredentials".

3. Team member search
This may be my environment setting but team members are registered in "Domain\UserShortname" instead of an email address.

Below is the code that I modified to fix those issues.
```
function GetReviewerId() {
    [CmdletBinding()]
    Param
    (
        [string]$reviewers
    )

    $serverUrl = $env:System_TeamFoundationCollectionUri
    $head = @{ Authorization = "Bearer $env:System_AccessToken" }
    # If it's TFS/AzureDevOps Server
    if ($serverUrl -notmatch "visualstudio.com" -and $serverUrl -notmatch "dev.azure.com") {

        $url = "$($env:System_TeamFoundationCollectionUri)_apis/projects/$($env:System_TeamProject)/teams?api-version=4.1"

        # $teams = Invoke-RestMethod -Method Get -Uri $url -Headers $head  -ContentType 'application/json'
        $teams = Invoke-RestMethod -Method Get -Uri $url -UseDefaultCredentials  -ContentType 'application/json'
        Write-Debug $reviewers
        $split = $reviewers.Split(';')
        $reviewersId = @()
        ForEach ($reviewer in $split) {
            # If the reviewer is user
            if ($reviewer.Contains("@")  -or $reviewer.Contains("\")) {
                $teams.value.ForEach( {
                    $teamUrl = "$($env:System_TeamFoundationCollectionUri)_apis/projects/$($env:System_TeamProject)/teams/$($_.id)/members?api-version=4.1"
                    # $team = Invoke-RestMethod -Method Get -Uri $teamUrl -Headers $head -ContentType 'application/json'
                    $team = Invoke-RestMethod -Method Get -Uri $teamUrl -UseDefaultCredentials -ContentType 'application/json'
    
                    # If the team contains only 1 user
                    if ($team.count -eq 1) {
                        if ($team.value.identity.uniqueName -eq $reviewer) {
                            $userId = $team.value.identity.id
                            Write-Host $userId -ForegroundColor Green
                            $reviewersId += @{ id = "$userId" }
                            break
                        }
                    }
                    else { # If the team contains more than 1 user 
                        $userId = $team.value.identity.Where( { $_.uniqueName -eq $reviewer }).id
                        if ($userId -ne $null) {
                            Write-Host $userId -ForegroundColor Green
                            $reviewersId += @{ id = "$userId" }
                            break
                        }
                    }
                })
            }
            # If the reviewer is team
            else {
                if ($teams.count -eq 1) {
                    if ($teams.value.name -eq $u) {
                        $teamId = $teams.value.id
                        Write-Host $teamId -ForegroundColor Green
                        $reviewersId += @{ id = "$userId" }
                    }
                }
                else {
                    $teamId = $teams.value.Where( { $_.name -eq $u }).id
                    Write-Host $teamId -ForegroundColor Green
                    $reviewersId += @{ id = "$teamId" }
                }
            }
        }
    }
    # If it's Azure Devops
    else {
        $url = "$($env:System_TeamFoundationCollectionUri)_apis/userentitlements?api-version=4.1-preview.1"
        # Check if it's the old url or the new url, reltaed to issue #21
        # And add "vsaex" to the rest api url 
        if ($url -match "visualstudio.com") {
            $url = $url.Replace(".visualstudio", ".vsaex.visualstudio")
        }
        else {
            $url = $url.Replace("//dev", "//vsaex.dev")
        }
        # $users = Invoke-RestMethod -Uri $url -Method Get -ContentType application/json -Headers $head
        $users = Invoke-RestMethod -Uri $url -Method Get -ContentType application/json -UseDefaultCredentials
        $teamsUrl = "$($env:System_TeamFoundationCollectionUri)_apis/projects/$($env:System_TeamProject)/teams?api-version=4.1-preview.1"
        # $teams = Invoke-RestMethod -Uri $teamsUrl -Method Get -ContentType application/json -Headers $head
        $teams = Invoke-RestMethod -Uri $teamsUrl -Method Get -ContentType application/json -UseDefaultCredentials
        Write-Debug $reviewers
        $split = $reviewers.Split(';')
        $reviewersId = @()
        ForEach ($reviewer in $split) {
            if ($reviewer.Contains("@") -or $reviewer.Contains("\")) {
                # Is user
                $userId = $users.value.Where( { $_.user.mailAddress -eq $reviewer }).id
                $reviewersId += @{ id = "$userId" }
            }
            else {
                # Is team
                $teamId = $teams.value.Where( { $_.name -eq $reviewer }).id
                $reviewersId += @{ id = "$teamId" }
            }
        }
    }
    return $reviewersId
}
```

**Comment by shayki5** [comment]
Hi @kulmam92,

Thank you so much for your comments and code!

1. My fault, I fixed it.

2. My fault again, system access token should work, I just didn't pass him, I fixed it.

3. In the task you should pass the email address in the reviewers field, I guess the email address are exist also, no?

I uploaded a new version now (1.2.82), please check if it works.
(I didn't use your code with the `-UseDefaultCredntials` because I prefer the task will use the access token)

Thank you,
Shayki

**Comment by shayki5** [comment]
Hi @kulmam92, could you check if it works for you?

**Comment by kulmam92** [comment]
@shayki5 Unfortunately, it's not.
I got error due to this line.

`$teamUrl = "$($env:System_TeamFoundationCollectionUri)_apis/projects/GitSample/teams/$($_.id)/members?api-version=4.1"`

**Comment by shayki5** [comment]
@kulmam92 Could you share the error please?

**Comment by kulmam92** [comment]
@shayki5 I got this error. GitSample should be an actual project name.

> ##[error]The remote server returned an error: (404) Not Found.

**Comment by shayki5** [comment]
Oh I missed it! Thanks.
I released a fix, could you check please?

**Comment by kulmam92** [comment]
@shayki5 I got this error.

> The term 'else' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by shayki5** [comment]
Thanks, @kulmam92!
It was a small bug in one of the brackets... I fixed it, please check now :)
Thank you so much!

**Comment by kulmam92** [comment]
@shayki5 
It's working now. Thank you for fixing this.

**Comment by shayki5** [comment]
@kulmam92 You're welcome :)
Thank you for reporting the issue!
